// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARA9q79eysRVlMNGAaLOyI6uFnMHvlD0Q',
    appId: '1:706941445226:web:4dc04c2d5853eda4911613',
    messagingSenderId: '706941445226',
    projectId: 'waleed-cigarette-agency',
    authDomain: 'waleed-cigarette-agency.firebaseapp.com',
    storageBucket: 'waleed-cigarette-agency.firebasestorage.app',
    measurementId: 'G-579EQKQSGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkphhyulGeUjV3If1fZQS8no69aHJ-7MI',
    appId: '1:706941445226:android:4be6b5dd5a2d4fd0911613',
    messagingSenderId: '706941445226',
    projectId: 'waleed-cigarette-agency',
    storageBucket: 'waleed-cigarette-agency.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AUGfDgsu2xq9HDj0dMExd1DmFAQEtAc',
    appId: '1:706941445226:ios:b9de6fd59c51da8a911613',
    messagingSenderId: '706941445226',
    projectId: 'waleed-cigarette-agency',
    storageBucket: 'waleed-cigarette-agency.firebasestorage.app',
    iosBundleId: 'com.example.cigaretteAgencyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6AUGfDgsu2xq9HDj0dMExd1DmFAQEtAc',
    appId: '1:706941445226:ios:b9de6fd59c51da8a911613',
    messagingSenderId: '706941445226',
    projectId: 'waleed-cigarette-agency',
    storageBucket: 'waleed-cigarette-agency.firebasestorage.app',
    iosBundleId: 'com.example.cigaretteAgencyManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARA9q79eysRVlMNGAaLOyI6uFnMHvlD0Q',
    appId: '1:706941445226:web:8d867b0a34f090b0911613',
    messagingSenderId: '706941445226',
    projectId: 'waleed-cigarette-agency',
    authDomain: 'waleed-cigarette-agency.firebaseapp.com',
    storageBucket: 'waleed-cigarette-agency.firebasestorage.app',
    measurementId: 'G-D8S2XMXFBD',
  );
}
